export type UUID = string;

export type MemorySourceType = "user" | "system" | "model" | "external";

export interface MemoryProvenance {
  source_type: MemorySourceType;
  source_id: string; // e.g., user ID, model name, or external URL
  timestamp: number; // Unix timestamp
  confidence: number; // 0.0 to 1.0
  derived_from?: UUID[]; // IDs of records this was derived from
  model_version?: string; // If generated by a model
}

export interface BaseMemoryRecord {
  id: UUID;
  createdAt: number;
  hash: string; // Content + Provenance hash
  provenance: MemoryProvenance;
}

export interface EpisodicRecord extends BaseMemoryRecord {
  type: "episodic";
  content: string; // Raw text or JSON string
  metadata?: Record<string, unknown>;
}

export interface SemanticRecord extends BaseMemoryRecord {
  type: "semantic";
  content: string; // Summarized or extracted knowledge
  embedding?: number[]; // Vector representation
  references: UUID[]; // Must reference at least one episodic record
}

export interface IdentityRecord extends BaseMemoryRecord {
  type: "identity";
  key: string; // e.g., "user_name", "preference_dark_mode"
  value: unknown;
  last_verified?: number;
}

export type MemoryRecord = EpisodicRecord | SemanticRecord | IdentityRecord;
